// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8V9Ct-aalNZmQqfeZYaq1g6Vrm9mZ6g',
    appId: '1:375873748608:web:adbcf7fcc14dddeb157065',
    messagingSenderId: '375873748608',
    projectId: 'instagram-clone-eac34',
    authDomain: 'instagram-clone-eac34.firebaseapp.com',
    storageBucket: 'instagram-clone-eac34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtkzNMxB4qRzLsgEx4KV9MIm43Fj1HKk',
    appId: '1:375873748608:android:7dbf4399a92c1384157065',
    messagingSenderId: '375873748608',
    projectId: 'instagram-clone-eac34',
    storageBucket: 'instagram-clone-eac34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYHp6r0V4SEGr6hw_sxhU4hXX7GEVxgI',
    appId: '1:375873748608:ios:7252aabbd941a5be157065',
    messagingSenderId: '375873748608',
    projectId: 'instagram-clone-eac34',
    storageBucket: 'instagram-clone-eac34.appspot.com',
    iosClientId: '375873748608-gkpakvt9mr4795ous1fc4bc9aj91g534.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYHp6r0V4SEGr6hw_sxhU4hXX7GEVxgI',
    appId: '1:375873748608:ios:55c4bea0158c3809157065',
    messagingSenderId: '375873748608',
    projectId: 'instagram-clone-eac34',
    storageBucket: 'instagram-clone-eac34.appspot.com',
    iosClientId: '375873748608-dj9v40acnnnjalk43fgim1ups586hndc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
